.section "scene10. lut" superfree
DemoScene10:
	.dw ((DemoScene10End-DemoScene10)/3)-2
	PTRLONG DemoScene10 scene10.000
	PTRLONG DemoScene10 scene10.001
	PTRLONG DemoScene10 scene10.002
	PTRLONG DemoScene10 scene10.003
	PTRLONG DemoScene10 scene10.004
	PTRLONG DemoScene10 scene10.005
	PTRLONG DemoScene10 scene10.006
	PTRLONG DemoScene10 scene10.007
	PTRLONG DemoScene10 scene10.008
	PTRLONG DemoScene10 scene10.009
	PTRLONG DemoScene10 scene10.010
	PTRLONG DemoScene10 scene10.011
	PTRLONG DemoScene10 scene10.012
	PTRLONG DemoScene10 scene10.013
	PTRLONG DemoScene10 scene10.014
	PTRLONG DemoScene10 scene10.015
	PTRLONG DemoScene10 scene10.016
	PTRLONG DemoScene10 scene10.017
	PTRLONG DemoScene10 scene10.018
	PTRLONG DemoScene10 scene10.019
	PTRLONG DemoScene10 scene10.020
	PTRLONG DemoScene10 scene10.021
	PTRLONG DemoScene10 scene10.022
	PTRLONG DemoScene10 scene10.023
	PTRLONG DemoScene10 scene10.024


DemoScene10End:

.ends

.section "scene10.000" superfree
	FILEINC scene10.000 "data/frames/scene10.000"
	FILEINC scene10.001 "data/frames/scene10.001"
	FILEINC scene10.002 "data/frames/scene10.002"
	FILEINC scene10.003 "data/frames/scene10.003"
	FILEINC scene10.004 "data/frames/scene10.004"
	FILEINC scene10.005 "data/frames/scene10.005"
	FILEINC scene10.006 "data/frames/scene10.006"
	FILEINC scene10.007 "data/frames/scene10.007"
	FILEINC scene10.008 "data/frames/scene10.008"
	FILEINC scene10.009 "data/frames/scene10.009"
.ends

.section "scene10.010" superfree
	FILEINC scene10.010 "data/frames/scene10.010"
	FILEINC scene10.011 "data/frames/scene10.011"
	FILEINC scene10.012 "data/frames/scene10.012"
	FILEINC scene10.013 "data/frames/scene10.013"
	FILEINC scene10.014 "data/frames/scene10.014"
	FILEINC scene10.015 "data/frames/scene10.015"
	FILEINC scene10.016 "data/frames/scene10.016"
	FILEINC scene10.017 "data/frames/scene10.017"
	FILEINC scene10.018 "data/frames/scene10.018"
	FILEINC scene10.019 "data/frames/scene10.019"
.ends

.section "scene10.020" superfree
	FILEINC scene10.020 "data/frames/scene10.020"
	FILEINC scene10.021 "data/frames/scene10.021"
	FILEINC scene10.022 "data/frames/scene10.022"
	FILEINC scene10.023 "data/frames/scene10.023"
	FILEINC scene10.024 "data/frames/scene10.024"

.ends
