.section "scene5. lut" superfree
DemoScene5:
	.dw ((DemoScene5End-DemoScene5)/3)-2
	PTRLONG DemoScene5 scene5.000
	PTRLONG DemoScene5 scene5.001
	PTRLONG DemoScene5 scene5.002
	PTRLONG DemoScene5 scene5.003
	PTRLONG DemoScene5 scene5.004
	PTRLONG DemoScene5 scene5.005
	PTRLONG DemoScene5 scene5.006
	PTRLONG DemoScene5 scene5.007
	PTRLONG DemoScene5 scene5.008
	PTRLONG DemoScene5 scene5.009
	PTRLONG DemoScene5 scene5.010
	PTRLONG DemoScene5 scene5.011
	PTRLONG DemoScene5 scene5.012
	PTRLONG DemoScene5 scene5.013
	PTRLONG DemoScene5 scene5.014
	PTRLONG DemoScene5 scene5.015
	PTRLONG DemoScene5 scene5.016
	PTRLONG DemoScene5 scene5.017
	PTRLONG DemoScene5 scene5.018
	PTRLONG DemoScene5 scene5.019
	PTRLONG DemoScene5 scene5.020
	PTRLONG DemoScene5 scene5.021
	PTRLONG DemoScene5 scene5.022
	PTRLONG DemoScene5 scene5.023
	PTRLONG DemoScene5 scene5.024
	PTRLONG DemoScene5 scene5.025
	PTRLONG DemoScene5 scene5.026
	PTRLONG DemoScene5 scene5.027
	PTRLONG DemoScene5 scene5.028
	PTRLONG DemoScene5 scene5.029
	PTRLONG DemoScene5 scene5.030
	PTRLONG DemoScene5 scene5.031
	PTRLONG DemoScene5 scene5.032
	PTRLONG DemoScene5 scene5.033
	PTRLONG DemoScene5 scene5.034
	PTRLONG DemoScene5 scene5.035
	PTRLONG DemoScene5 scene5.036
	PTRLONG DemoScene5 scene5.037
	PTRLONG DemoScene5 scene5.038
	PTRLONG DemoScene5 scene5.039
	PTRLONG DemoScene5 scene5.040
	PTRLONG DemoScene5 scene5.041
	PTRLONG DemoScene5 scene5.042
	PTRLONG DemoScene5 scene5.043
	PTRLONG DemoScene5 scene5.044
	PTRLONG DemoScene5 scene5.045
	PTRLONG DemoScene5 scene5.046
	PTRLONG DemoScene5 scene5.047
	PTRLONG DemoScene5 scene5.048
	PTRLONG DemoScene5 scene5.049
	PTRLONG DemoScene5 scene5.050
	PTRLONG DemoScene5 scene5.051
	PTRLONG DemoScene5 scene5.052
	PTRLONG DemoScene5 scene5.053
	PTRLONG DemoScene5 scene5.054
	PTRLONG DemoScene5 scene5.055
	PTRLONG DemoScene5 scene5.056
	PTRLONG DemoScene5 scene5.057
	PTRLONG DemoScene5 scene5.058
	PTRLONG DemoScene5 scene5.059
	PTRLONG DemoScene5 scene5.060
	PTRLONG DemoScene5 scene5.061
	PTRLONG DemoScene5 scene5.062
	PTRLONG DemoScene5 scene5.063
	PTRLONG DemoScene5 scene5.064
	PTRLONG DemoScene5 scene5.065
	PTRLONG DemoScene5 scene5.066
	PTRLONG DemoScene5 scene5.067
	PTRLONG DemoScene5 scene5.068
	PTRLONG DemoScene5 scene5.069
	PTRLONG DemoScene5 scene5.070
	PTRLONG DemoScene5 scene5.071
	PTRLONG DemoScene5 scene5.072
	PTRLONG DemoScene5 scene5.073
	PTRLONG DemoScene5 scene5.074
	PTRLONG DemoScene5 scene5.075
	PTRLONG DemoScene5 scene5.076
	PTRLONG DemoScene5 scene5.077
	PTRLONG DemoScene5 scene5.078
	PTRLONG DemoScene5 scene5.079
	PTRLONG DemoScene5 scene5.080
	PTRLONG DemoScene5 scene5.081
	PTRLONG DemoScene5 scene5.082
	PTRLONG DemoScene5 scene5.083
	PTRLONG DemoScene5 scene5.084
	PTRLONG DemoScene5 scene5.085
	PTRLONG DemoScene5 scene5.086
	PTRLONG DemoScene5 scene5.087
	PTRLONG DemoScene5 scene5.088
	PTRLONG DemoScene5 scene5.089
	PTRLONG DemoScene5 scene5.090
	PTRLONG DemoScene5 scene5.091
	PTRLONG DemoScene5 scene5.092
	PTRLONG DemoScene5 scene5.093
	PTRLONG DemoScene5 scene5.094
	PTRLONG DemoScene5 scene5.095
	PTRLONG DemoScene5 scene5.096
	PTRLONG DemoScene5 scene5.097
	PTRLONG DemoScene5 scene5.098
	PTRLONG DemoScene5 scene5.099

DemoScene5End:

.ends

.section "scene5.000" superfree
	FILEINC scene5.000 "data/frames/scene5.000"
	FILEINC scene5.001 "data/frames/scene5.001"
	FILEINC scene5.002 "data/frames/scene5.002"
	FILEINC scene5.003 "data/frames/scene5.003"
	FILEINC scene5.004 "data/frames/scene5.004"
	FILEINC scene5.005 "data/frames/scene5.005"
	FILEINC scene5.006 "data/frames/scene5.006"
	FILEINC scene5.007 "data/frames/scene5.007"
	FILEINC scene5.008 "data/frames/scene5.008"
	FILEINC scene5.009 "data/frames/scene5.009"
.ends

.section "scene5.010" superfree
	FILEINC scene5.010 "data/frames/scene5.010"
	FILEINC scene5.011 "data/frames/scene5.011"
	FILEINC scene5.012 "data/frames/scene5.012"
	FILEINC scene5.013 "data/frames/scene5.013"
	FILEINC scene5.014 "data/frames/scene5.014"
	FILEINC scene5.015 "data/frames/scene5.015"
	FILEINC scene5.016 "data/frames/scene5.016"
	FILEINC scene5.017 "data/frames/scene5.017"
	FILEINC scene5.018 "data/frames/scene5.018"
	FILEINC scene5.019 "data/frames/scene5.019"
.ends

.section "scene5.020" superfree
	FILEINC scene5.020 "data/frames/scene5.020"
	FILEINC scene5.021 "data/frames/scene5.021"
	FILEINC scene5.022 "data/frames/scene5.022"
	FILEINC scene5.023 "data/frames/scene5.023"
	FILEINC scene5.024 "data/frames/scene5.024"
	FILEINC scene5.025 "data/frames/scene5.025"
	FILEINC scene5.026 "data/frames/scene5.026"
	FILEINC scene5.027 "data/frames/scene5.027"
	FILEINC scene5.028 "data/frames/scene5.028"
	FILEINC scene5.029 "data/frames/scene5.029"
.ends


.section "scene5.030" superfree
	FILEINC scene5.030 "data/frames/scene5.030"
	FILEINC scene5.031 "data/frames/scene5.031"
	FILEINC scene5.032 "data/frames/scene5.032"
	FILEINC scene5.033 "data/frames/scene5.033"
	FILEINC scene5.034 "data/frames/scene5.034"
	FILEINC scene5.035 "data/frames/scene5.035"
	FILEINC scene5.036 "data/frames/scene5.036"
	FILEINC scene5.037 "data/frames/scene5.037"
	FILEINC scene5.038 "data/frames/scene5.038"
	FILEINC scene5.039 "data/frames/scene5.039"
.ends


.section "scene5.040" superfree
	FILEINC scene5.040 "data/frames/scene5.040"
	FILEINC scene5.041 "data/frames/scene5.041"
	FILEINC scene5.042 "data/frames/scene5.042"
	FILEINC scene5.043 "data/frames/scene5.043"
	FILEINC scene5.044 "data/frames/scene5.044"
	FILEINC scene5.045 "data/frames/scene5.045"
	FILEINC scene5.046 "data/frames/scene5.046"
	FILEINC scene5.047 "data/frames/scene5.047"
	FILEINC scene5.048 "data/frames/scene5.048"
	FILEINC scene5.049 "data/frames/scene5.049"
.ends


.section "scene5.050" superfree
	FILEINC scene5.050 "data/frames/scene5.050"
	FILEINC scene5.051 "data/frames/scene5.051"
	FILEINC scene5.052 "data/frames/scene5.052"
	FILEINC scene5.053 "data/frames/scene5.053"
	FILEINC scene5.054 "data/frames/scene5.054"
	FILEINC scene5.055 "data/frames/scene5.055"
	FILEINC scene5.056 "data/frames/scene5.056"
	FILEINC scene5.057 "data/frames/scene5.057"
	FILEINC scene5.058 "data/frames/scene5.058"
	FILEINC scene5.059 "data/frames/scene5.059"
.ends


.section "scene5.060" superfree
	FILEINC scene5.060 "data/frames/scene5.060"
	FILEINC scene5.061 "data/frames/scene5.061"
	FILEINC scene5.062 "data/frames/scene5.062"
	FILEINC scene5.063 "data/frames/scene5.063"
	FILEINC scene5.064 "data/frames/scene5.064"
	FILEINC scene5.065 "data/frames/scene5.065"
	FILEINC scene5.066 "data/frames/scene5.066"
	FILEINC scene5.067 "data/frames/scene5.067"
	FILEINC scene5.068 "data/frames/scene5.068"
	FILEINC scene5.069 "data/frames/scene5.069"
.ends


.section "scene5.070" superfree
	FILEINC scene5.070 "data/frames/scene5.070"
	FILEINC scene5.071 "data/frames/scene5.071"
	FILEINC scene5.072 "data/frames/scene5.072"
	FILEINC scene5.073 "data/frames/scene5.073"
	FILEINC scene5.074 "data/frames/scene5.074"
	FILEINC scene5.075 "data/frames/scene5.075"
	FILEINC scene5.076 "data/frames/scene5.076"
	FILEINC scene5.077 "data/frames/scene5.077"
	FILEINC scene5.078 "data/frames/scene5.078"
	FILEINC scene5.079 "data/frames/scene5.079"
.ends


.section "scene5.080" superfree
	FILEINC scene5.080 "data/frames/scene5.080"
	FILEINC scene5.081 "data/frames/scene5.081"
	FILEINC scene5.082 "data/frames/scene5.082"
	FILEINC scene5.083 "data/frames/scene5.083"
	FILEINC scene5.084 "data/frames/scene5.084"
	FILEINC scene5.085 "data/frames/scene5.085"
	FILEINC scene5.086 "data/frames/scene5.086"
	FILEINC scene5.087 "data/frames/scene5.087"
	FILEINC scene5.088 "data/frames/scene5.088"
	FILEINC scene5.089 "data/frames/scene5.089"
.ends


.section "scene5.090" superfree
	FILEINC scene5.090 "data/frames/scene5.090"
	FILEINC scene5.091 "data/frames/scene5.091"
	FILEINC scene5.092 "data/frames/scene5.092"
	FILEINC scene5.093 "data/frames/scene5.093"
	FILEINC scene5.094 "data/frames/scene5.094"
	FILEINC scene5.095 "data/frames/scene5.095"
	FILEINC scene5.096 "data/frames/scene5.096"
	FILEINC scene5.097 "data/frames/scene5.097"
	FILEINC scene5.098 "data/frames/scene5.098"
	FILEINC scene5.099 "data/frames/scene5.099"
.ends

