.section "scene8. lut" superfree
DemoScene8:
	.dw ((DemoScene8End-DemoScene8)/3)-2
	PTRLONG DemoScene8 scene8.000
	PTRLONG DemoScene8 scene8.001
	PTRLONG DemoScene8 scene8.002
	PTRLONG DemoScene8 scene8.003
	PTRLONG DemoScene8 scene8.004
	PTRLONG DemoScene8 scene8.005
	PTRLONG DemoScene8 scene8.006
	PTRLONG DemoScene8 scene8.007
	PTRLONG DemoScene8 scene8.008
	PTRLONG DemoScene8 scene8.009
	PTRLONG DemoScene8 scene8.010
	PTRLONG DemoScene8 scene8.011
	PTRLONG DemoScene8 scene8.012
	PTRLONG DemoScene8 scene8.013
	PTRLONG DemoScene8 scene8.014
	PTRLONG DemoScene8 scene8.015
	PTRLONG DemoScene8 scene8.016
	PTRLONG DemoScene8 scene8.017
	PTRLONG DemoScene8 scene8.018
	PTRLONG DemoScene8 scene8.019
	PTRLONG DemoScene8 scene8.020
	PTRLONG DemoScene8 scene8.021
	PTRLONG DemoScene8 scene8.022
	PTRLONG DemoScene8 scene8.023
	PTRLONG DemoScene8 scene8.024
	PTRLONG DemoScene8 scene8.025
	PTRLONG DemoScene8 scene8.026
	PTRLONG DemoScene8 scene8.027
	PTRLONG DemoScene8 scene8.028
	PTRLONG DemoScene8 scene8.029
	PTRLONG DemoScene8 scene8.030
	PTRLONG DemoScene8 scene8.031
	PTRLONG DemoScene8 scene8.032
	PTRLONG DemoScene8 scene8.033
	PTRLONG DemoScene8 scene8.034
	PTRLONG DemoScene8 scene8.035
	PTRLONG DemoScene8 scene8.036
	PTRLONG DemoScene8 scene8.037
	PTRLONG DemoScene8 scene8.038
	PTRLONG DemoScene8 scene8.039
	PTRLONG DemoScene8 scene8.040
	PTRLONG DemoScene8 scene8.041
	PTRLONG DemoScene8 scene8.042
	PTRLONG DemoScene8 scene8.043
	PTRLONG DemoScene8 scene8.044
	PTRLONG DemoScene8 scene8.045
	PTRLONG DemoScene8 scene8.046
	PTRLONG DemoScene8 scene8.047
	PTRLONG DemoScene8 scene8.048
	PTRLONG DemoScene8 scene8.049
	PTRLONG DemoScene8 scene8.050
	PTRLONG DemoScene8 scene8.051
	PTRLONG DemoScene8 scene8.052
	PTRLONG DemoScene8 scene8.053
	PTRLONG DemoScene8 scene8.054
	PTRLONG DemoScene8 scene8.055
	PTRLONG DemoScene8 scene8.056
	PTRLONG DemoScene8 scene8.057
	PTRLONG DemoScene8 scene8.058
	PTRLONG DemoScene8 scene8.059
	PTRLONG DemoScene8 scene8.060
	PTRLONG DemoScene8 scene8.061
	PTRLONG DemoScene8 scene8.062
	PTRLONG DemoScene8 scene8.063
	PTRLONG DemoScene8 scene8.064
	PTRLONG DemoScene8 scene8.065
	PTRLONG DemoScene8 scene8.066
	PTRLONG DemoScene8 scene8.067
	PTRLONG DemoScene8 scene8.068
	PTRLONG DemoScene8 scene8.069
	PTRLONG DemoScene8 scene8.070
	PTRLONG DemoScene8 scene8.071
	PTRLONG DemoScene8 scene8.072
	PTRLONG DemoScene8 scene8.073
	PTRLONG DemoScene8 scene8.074
	PTRLONG DemoScene8 scene8.075
	PTRLONG DemoScene8 scene8.076
	PTRLONG DemoScene8 scene8.077
	PTRLONG DemoScene8 scene8.078
	PTRLONG DemoScene8 scene8.079
	PTRLONG DemoScene8 scene8.080
	PTRLONG DemoScene8 scene8.081
	PTRLONG DemoScene8 scene8.082
	PTRLONG DemoScene8 scene8.083
	PTRLONG DemoScene8 scene8.084
	PTRLONG DemoScene8 scene8.085
	PTRLONG DemoScene8 scene8.086
	PTRLONG DemoScene8 scene8.087
	PTRLONG DemoScene8 scene8.088
	PTRLONG DemoScene8 scene8.089


DemoScene8End:

.ends

.section "scene8.000" superfree
	FILEINC scene8.000 "data/frames/scene8.000"
	FILEINC scene8.001 "data/frames/scene8.001"
	FILEINC scene8.002 "data/frames/scene8.002"
	FILEINC scene8.003 "data/frames/scene8.003"
	FILEINC scene8.004 "data/frames/scene8.004"
	FILEINC scene8.005 "data/frames/scene8.005"
	FILEINC scene8.006 "data/frames/scene8.006"
	FILEINC scene8.007 "data/frames/scene8.007"
	FILEINC scene8.008 "data/frames/scene8.008"
	FILEINC scene8.009 "data/frames/scene8.009"
.ends

.section "scene8.010" superfree
	FILEINC scene8.010 "data/frames/scene8.010"
	FILEINC scene8.011 "data/frames/scene8.011"
	FILEINC scene8.012 "data/frames/scene8.012"
	FILEINC scene8.013 "data/frames/scene8.013"
	FILEINC scene8.014 "data/frames/scene8.014"
	FILEINC scene8.015 "data/frames/scene8.015"
	FILEINC scene8.016 "data/frames/scene8.016"
	FILEINC scene8.017 "data/frames/scene8.017"
	FILEINC scene8.018 "data/frames/scene8.018"
	FILEINC scene8.019 "data/frames/scene8.019"
.ends

.section "scene8.020" superfree
	FILEINC scene8.020 "data/frames/scene8.020"
	FILEINC scene8.021 "data/frames/scene8.021"
	FILEINC scene8.022 "data/frames/scene8.022"
	FILEINC scene8.023 "data/frames/scene8.023"
	FILEINC scene8.024 "data/frames/scene8.024"
	FILEINC scene8.025 "data/frames/scene8.025"
	FILEINC scene8.026 "data/frames/scene8.026"
	FILEINC scene8.027 "data/frames/scene8.027"
	FILEINC scene8.028 "data/frames/scene8.028"
	FILEINC scene8.029 "data/frames/scene8.029"
.ends


.section "scene8.030" superfree
	FILEINC scene8.030 "data/frames/scene8.030"
	FILEINC scene8.031 "data/frames/scene8.031"
	FILEINC scene8.032 "data/frames/scene8.032"
	FILEINC scene8.033 "data/frames/scene8.033"
	FILEINC scene8.034 "data/frames/scene8.034"
	FILEINC scene8.035 "data/frames/scene8.035"
	FILEINC scene8.036 "data/frames/scene8.036"
	FILEINC scene8.037 "data/frames/scene8.037"
	FILEINC scene8.038 "data/frames/scene8.038"
	FILEINC scene8.039 "data/frames/scene8.039"
.ends


.section "scene8.040" superfree
	FILEINC scene8.040 "data/frames/scene8.040"
	FILEINC scene8.041 "data/frames/scene8.041"
	FILEINC scene8.042 "data/frames/scene8.042"
	FILEINC scene8.043 "data/frames/scene8.043"
	FILEINC scene8.044 "data/frames/scene8.044"
	FILEINC scene8.045 "data/frames/scene8.045"
	FILEINC scene8.046 "data/frames/scene8.046"
	FILEINC scene8.047 "data/frames/scene8.047"
	FILEINC scene8.048 "data/frames/scene8.048"
	FILEINC scene8.049 "data/frames/scene8.049"
.ends


.section "scene8.050" superfree
	FILEINC scene8.050 "data/frames/scene8.050"
	FILEINC scene8.051 "data/frames/scene8.051"
	FILEINC scene8.052 "data/frames/scene8.052"
	FILEINC scene8.053 "data/frames/scene8.053"
	FILEINC scene8.054 "data/frames/scene8.054"
	FILEINC scene8.055 "data/frames/scene8.055"
	FILEINC scene8.056 "data/frames/scene8.056"
	FILEINC scene8.057 "data/frames/scene8.057"
	FILEINC scene8.058 "data/frames/scene8.058"
	FILEINC scene8.059 "data/frames/scene8.059"
.ends


.section "scene8.060" superfree
	FILEINC scene8.060 "data/frames/scene8.060"
	FILEINC scene8.061 "data/frames/scene8.061"
	FILEINC scene8.062 "data/frames/scene8.062"
	FILEINC scene8.063 "data/frames/scene8.063"
	FILEINC scene8.064 "data/frames/scene8.064"
	FILEINC scene8.065 "data/frames/scene8.065"
	FILEINC scene8.066 "data/frames/scene8.066"
	FILEINC scene8.067 "data/frames/scene8.067"
	FILEINC scene8.068 "data/frames/scene8.068"
	FILEINC scene8.069 "data/frames/scene8.069"
.ends


.section "scene8.070" superfree
	FILEINC scene8.070 "data/frames/scene8.070"
	FILEINC scene8.071 "data/frames/scene8.071"
	FILEINC scene8.072 "data/frames/scene8.072"
	FILEINC scene8.073 "data/frames/scene8.073"
	FILEINC scene8.074 "data/frames/scene8.074"
	FILEINC scene8.075 "data/frames/scene8.075"
	FILEINC scene8.076 "data/frames/scene8.076"
	FILEINC scene8.077 "data/frames/scene8.077"
	FILEINC scene8.078 "data/frames/scene8.078"
	FILEINC scene8.079 "data/frames/scene8.079"
.ends


.section "scene8.080" superfree
	FILEINC scene8.080 "data/frames/scene8.080"
	FILEINC scene8.081 "data/frames/scene8.081"
	FILEINC scene8.082 "data/frames/scene8.082"
	FILEINC scene8.083 "data/frames/scene8.083"
	FILEINC scene8.084 "data/frames/scene8.084"
	FILEINC scene8.085 "data/frames/scene8.085"
	FILEINC scene8.086 "data/frames/scene8.086"
	FILEINC scene8.087 "data/frames/scene8.087"
	FILEINC scene8.088 "data/frames/scene8.088"
	FILEINC scene8.089 "data/frames/scene8.089"
.ends
