.section "scene4. lut" superfree
DemoScene4:
	.dw ((DemoScene4End-DemoScene4)/3)-2
	PTRLONG DemoScene4 scene4.000
	PTRLONG DemoScene4 scene4.001
	PTRLONG DemoScene4 scene4.002
	PTRLONG DemoScene4 scene4.003
	PTRLONG DemoScene4 scene4.004
	PTRLONG DemoScene4 scene4.005
	PTRLONG DemoScene4 scene4.006
	PTRLONG DemoScene4 scene4.007
	PTRLONG DemoScene4 scene4.008
	PTRLONG DemoScene4 scene4.009
	PTRLONG DemoScene4 scene4.010
	PTRLONG DemoScene4 scene4.011
	PTRLONG DemoScene4 scene4.012
	PTRLONG DemoScene4 scene4.013
	PTRLONG DemoScene4 scene4.014
	PTRLONG DemoScene4 scene4.015
	PTRLONG DemoScene4 scene4.016
	PTRLONG DemoScene4 scene4.017
	PTRLONG DemoScene4 scene4.018
	PTRLONG DemoScene4 scene4.019
	PTRLONG DemoScene4 scene4.020
	PTRLONG DemoScene4 scene4.021
	PTRLONG DemoScene4 scene4.022
	PTRLONG DemoScene4 scene4.023
	PTRLONG DemoScene4 scene4.024
	PTRLONG DemoScene4 scene4.025
	PTRLONG DemoScene4 scene4.026
	PTRLONG DemoScene4 scene4.027
	PTRLONG DemoScene4 scene4.028
	PTRLONG DemoScene4 scene4.029
	PTRLONG DemoScene4 scene4.030
	PTRLONG DemoScene4 scene4.031
	PTRLONG DemoScene4 scene4.032
	PTRLONG DemoScene4 scene4.033
	PTRLONG DemoScene4 scene4.034
	PTRLONG DemoScene4 scene4.035
	PTRLONG DemoScene4 scene4.036
	PTRLONG DemoScene4 scene4.037
	PTRLONG DemoScene4 scene4.038
	PTRLONG DemoScene4 scene4.039
	PTRLONG DemoScene4 scene4.040
	PTRLONG DemoScene4 scene4.041
	PTRLONG DemoScene4 scene4.042
	PTRLONG DemoScene4 scene4.043
	PTRLONG DemoScene4 scene4.044
	PTRLONG DemoScene4 scene4.045
	PTRLONG DemoScene4 scene4.046
	PTRLONG DemoScene4 scene4.047
	PTRLONG DemoScene4 scene4.048
	PTRLONG DemoScene4 scene4.049
	PTRLONG DemoScene4 scene4.050
	PTRLONG DemoScene4 scene4.051
	PTRLONG DemoScene4 scene4.052
	PTRLONG DemoScene4 scene4.053
	PTRLONG DemoScene4 scene4.054
	PTRLONG DemoScene4 scene4.055
	PTRLONG DemoScene4 scene4.056
	PTRLONG DemoScene4 scene4.057
	PTRLONG DemoScene4 scene4.058
	PTRLONG DemoScene4 scene4.059
	PTRLONG DemoScene4 scene4.060
	PTRLONG DemoScene4 scene4.061
	PTRLONG DemoScene4 scene4.062
	PTRLONG DemoScene4 scene4.063
	PTRLONG DemoScene4 scene4.064
	PTRLONG DemoScene4 scene4.065
	PTRLONG DemoScene4 scene4.066
	PTRLONG DemoScene4 scene4.067
	PTRLONG DemoScene4 scene4.068
	PTRLONG DemoScene4 scene4.069
	PTRLONG DemoScene4 scene4.070
	PTRLONG DemoScene4 scene4.071
	PTRLONG DemoScene4 scene4.072
	PTRLONG DemoScene4 scene4.073
	PTRLONG DemoScene4 scene4.074
	PTRLONG DemoScene4 scene4.075
	PTRLONG DemoScene4 scene4.076
	PTRLONG DemoScene4 scene4.077
	PTRLONG DemoScene4 scene4.078
	PTRLONG DemoScene4 scene4.079
	PTRLONG DemoScene4 scene4.080
	PTRLONG DemoScene4 scene4.081
	PTRLONG DemoScene4 scene4.082
	PTRLONG DemoScene4 scene4.083
	PTRLONG DemoScene4 scene4.084
	PTRLONG DemoScene4 scene4.085
	PTRLONG DemoScene4 scene4.086
	PTRLONG DemoScene4 scene4.087
	PTRLONG DemoScene4 scene4.088
	PTRLONG DemoScene4 scene4.089
	PTRLONG DemoScene4 scene4.090
	PTRLONG DemoScene4 scene4.091
	PTRLONG DemoScene4 scene4.092
	PTRLONG DemoScene4 scene4.093
	PTRLONG DemoScene4 scene4.094
	PTRLONG DemoScene4 scene4.095
	PTRLONG DemoScene4 scene4.096
	PTRLONG DemoScene4 scene4.097
	PTRLONG DemoScene4 scene4.098
	PTRLONG DemoScene4 scene4.099

DemoScene4End:

.ends

.section "scene4.000" superfree
	FILEINC scene4.000 "data/frames/scene4.000"
	FILEINC scene4.001 "data/frames/scene4.001"
	FILEINC scene4.002 "data/frames/scene4.002"
	FILEINC scene4.003 "data/frames/scene4.003"
	FILEINC scene4.004 "data/frames/scene4.004"
	FILEINC scene4.005 "data/frames/scene4.005"
	FILEINC scene4.006 "data/frames/scene4.006"
	FILEINC scene4.007 "data/frames/scene4.007"
	FILEINC scene4.008 "data/frames/scene4.008"
	FILEINC scene4.009 "data/frames/scene4.009"
.ends

.section "scene4.010" superfree
	FILEINC scene4.010 "data/frames/scene4.010"
	FILEINC scene4.011 "data/frames/scene4.011"
	FILEINC scene4.012 "data/frames/scene4.012"
	FILEINC scene4.013 "data/frames/scene4.013"
	FILEINC scene4.014 "data/frames/scene4.014"
	FILEINC scene4.015 "data/frames/scene4.015"
	FILEINC scene4.016 "data/frames/scene4.016"
	FILEINC scene4.017 "data/frames/scene4.017"
	FILEINC scene4.018 "data/frames/scene4.018"
	FILEINC scene4.019 "data/frames/scene4.019"
.ends

.section "scene4.020" superfree
	FILEINC scene4.020 "data/frames/scene4.020"
	FILEINC scene4.021 "data/frames/scene4.021"
	FILEINC scene4.022 "data/frames/scene4.022"
	FILEINC scene4.023 "data/frames/scene4.023"
	FILEINC scene4.024 "data/frames/scene4.024"
	FILEINC scene4.025 "data/frames/scene4.025"
	FILEINC scene4.026 "data/frames/scene4.026"
	FILEINC scene4.027 "data/frames/scene4.027"
	FILEINC scene4.028 "data/frames/scene4.028"
	FILEINC scene4.029 "data/frames/scene4.029"
.ends


.section "scene4.030" superfree
	FILEINC scene4.030 "data/frames/scene4.030"
	FILEINC scene4.031 "data/frames/scene4.031"
	FILEINC scene4.032 "data/frames/scene4.032"
	FILEINC scene4.033 "data/frames/scene4.033"
	FILEINC scene4.034 "data/frames/scene4.034"
	FILEINC scene4.035 "data/frames/scene4.035"
	FILEINC scene4.036 "data/frames/scene4.036"
	FILEINC scene4.037 "data/frames/scene4.037"
	FILEINC scene4.038 "data/frames/scene4.038"
	FILEINC scene4.039 "data/frames/scene4.039"
.ends


.section "scene4.040" superfree
	FILEINC scene4.040 "data/frames/scene4.040"
	FILEINC scene4.041 "data/frames/scene4.041"
	FILEINC scene4.042 "data/frames/scene4.042"
	FILEINC scene4.043 "data/frames/scene4.043"
	FILEINC scene4.044 "data/frames/scene4.044"
	FILEINC scene4.045 "data/frames/scene4.045"
	FILEINC scene4.046 "data/frames/scene4.046"
	FILEINC scene4.047 "data/frames/scene4.047"
	FILEINC scene4.048 "data/frames/scene4.048"
	FILEINC scene4.049 "data/frames/scene4.049"
.ends


.section "scene4.050" superfree
	FILEINC scene4.050 "data/frames/scene4.050"
	FILEINC scene4.051 "data/frames/scene4.051"
	FILEINC scene4.052 "data/frames/scene4.052"
	FILEINC scene4.053 "data/frames/scene4.053"
	FILEINC scene4.054 "data/frames/scene4.054"
	FILEINC scene4.055 "data/frames/scene4.055"
	FILEINC scene4.056 "data/frames/scene4.056"
	FILEINC scene4.057 "data/frames/scene4.057"
	FILEINC scene4.058 "data/frames/scene4.058"
	FILEINC scene4.059 "data/frames/scene4.059"
.ends


.section "scene4.060" superfree
	FILEINC scene4.060 "data/frames/scene4.060"
	FILEINC scene4.061 "data/frames/scene4.061"
	FILEINC scene4.062 "data/frames/scene4.062"
	FILEINC scene4.063 "data/frames/scene4.063"
	FILEINC scene4.064 "data/frames/scene4.064"
	FILEINC scene4.065 "data/frames/scene4.065"
	FILEINC scene4.066 "data/frames/scene4.066"
	FILEINC scene4.067 "data/frames/scene4.067"
	FILEINC scene4.068 "data/frames/scene4.068"
	FILEINC scene4.069 "data/frames/scene4.069"
.ends


.section "scene4.070" superfree
	FILEINC scene4.070 "data/frames/scene4.070"
	FILEINC scene4.071 "data/frames/scene4.071"
	FILEINC scene4.072 "data/frames/scene4.072"
	FILEINC scene4.073 "data/frames/scene4.073"
	FILEINC scene4.074 "data/frames/scene4.074"
	FILEINC scene4.075 "data/frames/scene4.075"
	FILEINC scene4.076 "data/frames/scene4.076"
	FILEINC scene4.077 "data/frames/scene4.077"
	FILEINC scene4.078 "data/frames/scene4.078"
	FILEINC scene4.079 "data/frames/scene4.079"
.ends


.section "scene4.080" superfree
	FILEINC scene4.080 "data/frames/scene4.080"
	FILEINC scene4.081 "data/frames/scene4.081"
	FILEINC scene4.082 "data/frames/scene4.082"
	FILEINC scene4.083 "data/frames/scene4.083"
	FILEINC scene4.084 "data/frames/scene4.084"
	FILEINC scene4.085 "data/frames/scene4.085"
	FILEINC scene4.086 "data/frames/scene4.086"
	FILEINC scene4.087 "data/frames/scene4.087"
	FILEINC scene4.088 "data/frames/scene4.088"
	FILEINC scene4.089 "data/frames/scene4.089"
.ends


.section "scene4.090" superfree
	FILEINC scene4.090 "data/frames/scene4.090"
	FILEINC scene4.091 "data/frames/scene4.091"
	FILEINC scene4.092 "data/frames/scene4.092"
	FILEINC scene4.093 "data/frames/scene4.093"
	FILEINC scene4.094 "data/frames/scene4.094"
	FILEINC scene4.095 "data/frames/scene4.095"
	FILEINC scene4.096 "data/frames/scene4.096"
	FILEINC scene4.097 "data/frames/scene4.097"
	FILEINC scene4.098 "data/frames/scene4.098"
	FILEINC scene4.099 "data/frames/scene4.099"
.ends

