.section "scene9. lut" superfree
DemoScene9:
	.dw ((DemoScene9End-DemoScene9)/3)-2
	PTRLONG DemoScene9 scene9.000
	PTRLONG DemoScene9 scene9.001
	PTRLONG DemoScene9 scene9.002
	PTRLONG DemoScene9 scene9.003
	PTRLONG DemoScene9 scene9.004
	PTRLONG DemoScene9 scene9.005
	PTRLONG DemoScene9 scene9.006
	PTRLONG DemoScene9 scene9.007
	PTRLONG DemoScene9 scene9.008
	PTRLONG DemoScene9 scene9.009
	PTRLONG DemoScene9 scene9.010
	PTRLONG DemoScene9 scene9.011
	PTRLONG DemoScene9 scene9.012
	PTRLONG DemoScene9 scene9.013
	PTRLONG DemoScene9 scene9.014
	PTRLONG DemoScene9 scene9.015
	PTRLONG DemoScene9 scene9.016
	PTRLONG DemoScene9 scene9.017
	PTRLONG DemoScene9 scene9.018
	PTRLONG DemoScene9 scene9.019
	PTRLONG DemoScene9 scene9.020
	PTRLONG DemoScene9 scene9.021
	PTRLONG DemoScene9 scene9.022
	PTRLONG DemoScene9 scene9.023
	PTRLONG DemoScene9 scene9.024
	PTRLONG DemoScene9 scene9.025
	PTRLONG DemoScene9 scene9.026
	PTRLONG DemoScene9 scene9.027
	PTRLONG DemoScene9 scene9.028
	PTRLONG DemoScene9 scene9.029
	PTRLONG DemoScene9 scene9.030
	PTRLONG DemoScene9 scene9.031
	PTRLONG DemoScene9 scene9.032
	PTRLONG DemoScene9 scene9.033
	PTRLONG DemoScene9 scene9.034
	PTRLONG DemoScene9 scene9.035
	PTRLONG DemoScene9 scene9.036
	PTRLONG DemoScene9 scene9.037
	PTRLONG DemoScene9 scene9.038
	PTRLONG DemoScene9 scene9.039
	PTRLONG DemoScene9 scene9.040
	PTRLONG DemoScene9 scene9.041
	PTRLONG DemoScene9 scene9.042
	PTRLONG DemoScene9 scene9.043
	PTRLONG DemoScene9 scene9.044
	PTRLONG DemoScene9 scene9.045
	PTRLONG DemoScene9 scene9.046
	PTRLONG DemoScene9 scene9.047
	PTRLONG DemoScene9 scene9.048
	PTRLONG DemoScene9 scene9.049

DemoScene9End:

.ends

.section "scene9.000" superfree
	FILEINC scene9.000 "data/frames/scene9.000"
	FILEINC scene9.001 "data/frames/scene9.001"
	FILEINC scene9.002 "data/frames/scene9.002"
	FILEINC scene9.003 "data/frames/scene9.003"
	FILEINC scene9.004 "data/frames/scene9.004"
	FILEINC scene9.005 "data/frames/scene9.005"
	FILEINC scene9.006 "data/frames/scene9.006"
	FILEINC scene9.007 "data/frames/scene9.007"
	FILEINC scene9.008 "data/frames/scene9.008"
	FILEINC scene9.009 "data/frames/scene9.009"
.ends

.section "scene9.010" superfree
	FILEINC scene9.010 "data/frames/scene9.010"
	FILEINC scene9.011 "data/frames/scene9.011"
	FILEINC scene9.012 "data/frames/scene9.012"
	FILEINC scene9.013 "data/frames/scene9.013"
	FILEINC scene9.014 "data/frames/scene9.014"
	FILEINC scene9.015 "data/frames/scene9.015"
	FILEINC scene9.016 "data/frames/scene9.016"
	FILEINC scene9.017 "data/frames/scene9.017"
	FILEINC scene9.018 "data/frames/scene9.018"
	FILEINC scene9.019 "data/frames/scene9.019"
.ends

.section "scene9.020" superfree
	FILEINC scene9.020 "data/frames/scene9.020"
	FILEINC scene9.021 "data/frames/scene9.021"
	FILEINC scene9.022 "data/frames/scene9.022"
	FILEINC scene9.023 "data/frames/scene9.023"
	FILEINC scene9.024 "data/frames/scene9.024"
	FILEINC scene9.025 "data/frames/scene9.025"
	FILEINC scene9.026 "data/frames/scene9.026"
	FILEINC scene9.027 "data/frames/scene9.027"
	FILEINC scene9.028 "data/frames/scene9.028"
	FILEINC scene9.029 "data/frames/scene9.029"
.ends


.section "scene9.030" superfree
	FILEINC scene9.030 "data/frames/scene9.030"
	FILEINC scene9.031 "data/frames/scene9.031"
	FILEINC scene9.032 "data/frames/scene9.032"
	FILEINC scene9.033 "data/frames/scene9.033"
	FILEINC scene9.034 "data/frames/scene9.034"
	FILEINC scene9.035 "data/frames/scene9.035"
	FILEINC scene9.036 "data/frames/scene9.036"
	FILEINC scene9.037 "data/frames/scene9.037"
	FILEINC scene9.038 "data/frames/scene9.038"
	FILEINC scene9.039 "data/frames/scene9.039"
.ends


.section "scene9.040" superfree
	FILEINC scene9.040 "data/frames/scene9.040"
	FILEINC scene9.041 "data/frames/scene9.041"
	FILEINC scene9.042 "data/frames/scene9.042"
	FILEINC scene9.043 "data/frames/scene9.043"
	FILEINC scene9.044 "data/frames/scene9.044"
	FILEINC scene9.045 "data/frames/scene9.045"
	FILEINC scene9.046 "data/frames/scene9.046"
	FILEINC scene9.047 "data/frames/scene9.047"
	FILEINC scene9.048 "data/frames/scene9.048"
	FILEINC scene9.049 "data/frames/scene9.049"
.ends

