.section "scene3. lut" superfree
DemoScene3:
	.dw ((DemoScene3End-DemoScene3)/3)-2
	PTRLONG DemoScene3 scene3.000
	PTRLONG DemoScene3 scene3.001
	PTRLONG DemoScene3 scene3.002
	PTRLONG DemoScene3 scene3.003
	PTRLONG DemoScene3 scene3.004
	PTRLONG DemoScene3 scene3.005
	PTRLONG DemoScene3 scene3.006
	PTRLONG DemoScene3 scene3.007
	PTRLONG DemoScene3 scene3.008
	PTRLONG DemoScene3 scene3.009
	PTRLONG DemoScene3 scene3.010
	PTRLONG DemoScene3 scene3.011
	PTRLONG DemoScene3 scene3.012
	PTRLONG DemoScene3 scene3.013
	PTRLONG DemoScene3 scene3.014
	PTRLONG DemoScene3 scene3.015
	PTRLONG DemoScene3 scene3.016
	PTRLONG DemoScene3 scene3.017
	PTRLONG DemoScene3 scene3.018
	PTRLONG DemoScene3 scene3.019
	PTRLONG DemoScene3 scene3.020
	PTRLONG DemoScene3 scene3.021
	PTRLONG DemoScene3 scene3.022
	PTRLONG DemoScene3 scene3.023
	PTRLONG DemoScene3 scene3.024
	PTRLONG DemoScene3 scene3.025
	PTRLONG DemoScene3 scene3.026
	PTRLONG DemoScene3 scene3.027
	PTRLONG DemoScene3 scene3.028
	PTRLONG DemoScene3 scene3.029
	PTRLONG DemoScene3 scene3.030
	PTRLONG DemoScene3 scene3.031
	PTRLONG DemoScene3 scene3.032
	PTRLONG DemoScene3 scene3.033
	PTRLONG DemoScene3 scene3.034
	PTRLONG DemoScene3 scene3.035
	PTRLONG DemoScene3 scene3.036
	PTRLONG DemoScene3 scene3.037
	PTRLONG DemoScene3 scene3.038
	PTRLONG DemoScene3 scene3.039
	PTRLONG DemoScene3 scene3.040
	PTRLONG DemoScene3 scene3.041
	PTRLONG DemoScene3 scene3.042
	PTRLONG DemoScene3 scene3.043
	PTRLONG DemoScene3 scene3.044
	PTRLONG DemoScene3 scene3.045
	PTRLONG DemoScene3 scene3.046
	PTRLONG DemoScene3 scene3.047
	PTRLONG DemoScene3 scene3.048
	PTRLONG DemoScene3 scene3.049
	PTRLONG DemoScene3 scene3.050
	PTRLONG DemoScene3 scene3.051
	PTRLONG DemoScene3 scene3.052
	PTRLONG DemoScene3 scene3.053
	PTRLONG DemoScene3 scene3.054
	PTRLONG DemoScene3 scene3.055
	PTRLONG DemoScene3 scene3.056
	PTRLONG DemoScene3 scene3.057
	PTRLONG DemoScene3 scene3.058
	PTRLONG DemoScene3 scene3.059
	PTRLONG DemoScene3 scene3.060
	PTRLONG DemoScene3 scene3.061
	PTRLONG DemoScene3 scene3.062
	PTRLONG DemoScene3 scene3.063
	PTRLONG DemoScene3 scene3.064
	PTRLONG DemoScene3 scene3.065
	PTRLONG DemoScene3 scene3.066
	PTRLONG DemoScene3 scene3.067
	PTRLONG DemoScene3 scene3.068
	PTRLONG DemoScene3 scene3.069
	PTRLONG DemoScene3 scene3.070
	PTRLONG DemoScene3 scene3.071
	PTRLONG DemoScene3 scene3.072
	PTRLONG DemoScene3 scene3.073
	PTRLONG DemoScene3 scene3.074
	PTRLONG DemoScene3 scene3.075
	PTRLONG DemoScene3 scene3.076
	PTRLONG DemoScene3 scene3.077
	PTRLONG DemoScene3 scene3.078
	PTRLONG DemoScene3 scene3.079
	PTRLONG DemoScene3 scene3.080
	PTRLONG DemoScene3 scene3.081
	PTRLONG DemoScene3 scene3.082
	PTRLONG DemoScene3 scene3.083
	PTRLONG DemoScene3 scene3.084
	PTRLONG DemoScene3 scene3.085
	PTRLONG DemoScene3 scene3.086
	PTRLONG DemoScene3 scene3.087
	PTRLONG DemoScene3 scene3.088
	PTRLONG DemoScene3 scene3.089
	PTRLONG DemoScene3 scene3.090
	PTRLONG DemoScene3 scene3.091
	PTRLONG DemoScene3 scene3.092
	PTRLONG DemoScene3 scene3.093
	PTRLONG DemoScene3 scene3.094
	PTRLONG DemoScene3 scene3.095
	PTRLONG DemoScene3 scene3.096
	PTRLONG DemoScene3 scene3.097
	PTRLONG DemoScene3 scene3.098
	PTRLONG DemoScene3 scene3.099
	PTRLONG DemoScene3 scene3.100
	PTRLONG DemoScene3 scene3.101
	PTRLONG DemoScene3 scene3.102
	PTRLONG DemoScene3 scene3.103
	PTRLONG DemoScene3 scene3.104
	PTRLONG DemoScene3 scene3.105
	PTRLONG DemoScene3 scene3.106
	PTRLONG DemoScene3 scene3.107
	PTRLONG DemoScene3 scene3.108
	PTRLONG DemoScene3 scene3.109


DemoScene3End:

.ends

.section "scene3.000" superfree
	FILEINC scene3.000 "data/frames/scene3.000"
	FILEINC scene3.001 "data/frames/scene3.001"
	FILEINC scene3.002 "data/frames/scene3.002"
	FILEINC scene3.003 "data/frames/scene3.003"
	FILEINC scene3.004 "data/frames/scene3.004"
	FILEINC scene3.005 "data/frames/scene3.005"
	FILEINC scene3.006 "data/frames/scene3.006"
	FILEINC scene3.007 "data/frames/scene3.007"
	FILEINC scene3.008 "data/frames/scene3.008"
	FILEINC scene3.009 "data/frames/scene3.009"
.ends

.section "scene3.010" superfree
	FILEINC scene3.010 "data/frames/scene3.010"
	FILEINC scene3.011 "data/frames/scene3.011"
	FILEINC scene3.012 "data/frames/scene3.012"
	FILEINC scene3.013 "data/frames/scene3.013"
	FILEINC scene3.014 "data/frames/scene3.014"
	FILEINC scene3.015 "data/frames/scene3.015"
	FILEINC scene3.016 "data/frames/scene3.016"
	FILEINC scene3.017 "data/frames/scene3.017"
	FILEINC scene3.018 "data/frames/scene3.018"
	FILEINC scene3.019 "data/frames/scene3.019"
.ends

.section "scene3.020" superfree
	FILEINC scene3.020 "data/frames/scene3.020"
	FILEINC scene3.021 "data/frames/scene3.021"
	FILEINC scene3.022 "data/frames/scene3.022"
	FILEINC scene3.023 "data/frames/scene3.023"
	FILEINC scene3.024 "data/frames/scene3.024"
	FILEINC scene3.025 "data/frames/scene3.025"
	FILEINC scene3.026 "data/frames/scene3.026"
	FILEINC scene3.027 "data/frames/scene3.027"
	FILEINC scene3.028 "data/frames/scene3.028"
	FILEINC scene3.029 "data/frames/scene3.029"
.ends


.section "scene3.030" superfree
	FILEINC scene3.030 "data/frames/scene3.030"
	FILEINC scene3.031 "data/frames/scene3.031"
	FILEINC scene3.032 "data/frames/scene3.032"
	FILEINC scene3.033 "data/frames/scene3.033"
	FILEINC scene3.034 "data/frames/scene3.034"
	FILEINC scene3.035 "data/frames/scene3.035"
	FILEINC scene3.036 "data/frames/scene3.036"
	FILEINC scene3.037 "data/frames/scene3.037"
	FILEINC scene3.038 "data/frames/scene3.038"
	FILEINC scene3.039 "data/frames/scene3.039"
.ends


.section "scene3.040" superfree
	FILEINC scene3.040 "data/frames/scene3.040"
	FILEINC scene3.041 "data/frames/scene3.041"
	FILEINC scene3.042 "data/frames/scene3.042"
	FILEINC scene3.043 "data/frames/scene3.043"
	FILEINC scene3.044 "data/frames/scene3.044"
	FILEINC scene3.045 "data/frames/scene3.045"
	FILEINC scene3.046 "data/frames/scene3.046"
	FILEINC scene3.047 "data/frames/scene3.047"
	FILEINC scene3.048 "data/frames/scene3.048"
	FILEINC scene3.049 "data/frames/scene3.049"
.ends


.section "scene3.050" superfree
	FILEINC scene3.050 "data/frames/scene3.050"
	FILEINC scene3.051 "data/frames/scene3.051"
	FILEINC scene3.052 "data/frames/scene3.052"
	FILEINC scene3.053 "data/frames/scene3.053"
	FILEINC scene3.054 "data/frames/scene3.054"
	FILEINC scene3.055 "data/frames/scene3.055"
	FILEINC scene3.056 "data/frames/scene3.056"
	FILEINC scene3.057 "data/frames/scene3.057"
	FILEINC scene3.058 "data/frames/scene3.058"
	FILEINC scene3.059 "data/frames/scene3.059"
.ends


.section "scene3.060" superfree
	FILEINC scene3.060 "data/frames/scene3.060"
	FILEINC scene3.061 "data/frames/scene3.061"
	FILEINC scene3.062 "data/frames/scene3.062"
	FILEINC scene3.063 "data/frames/scene3.063"
	FILEINC scene3.064 "data/frames/scene3.064"
	FILEINC scene3.065 "data/frames/scene3.065"
	FILEINC scene3.066 "data/frames/scene3.066"
	FILEINC scene3.067 "data/frames/scene3.067"
	FILEINC scene3.068 "data/frames/scene3.068"
	FILEINC scene3.069 "data/frames/scene3.069"
.ends


.section "scene3.070" superfree
	FILEINC scene3.070 "data/frames/scene3.070"
	FILEINC scene3.071 "data/frames/scene3.071"
	FILEINC scene3.072 "data/frames/scene3.072"
	FILEINC scene3.073 "data/frames/scene3.073"
	FILEINC scene3.074 "data/frames/scene3.074"
	FILEINC scene3.075 "data/frames/scene3.075"
	FILEINC scene3.076 "data/frames/scene3.076"
	FILEINC scene3.077 "data/frames/scene3.077"
	FILEINC scene3.078 "data/frames/scene3.078"
	FILEINC scene3.079 "data/frames/scene3.079"
.ends


.section "scene3.080" superfree
	FILEINC scene3.080 "data/frames/scene3.080"
	FILEINC scene3.081 "data/frames/scene3.081"
	FILEINC scene3.082 "data/frames/scene3.082"
	FILEINC scene3.083 "data/frames/scene3.083"
	FILEINC scene3.084 "data/frames/scene3.084"
	FILEINC scene3.085 "data/frames/scene3.085"
	FILEINC scene3.086 "data/frames/scene3.086"
	FILEINC scene3.087 "data/frames/scene3.087"
	FILEINC scene3.088 "data/frames/scene3.088"
	FILEINC scene3.089 "data/frames/scene3.089"
.ends


.section "scene3.090" superfree
	FILEINC scene3.090 "data/frames/scene3.090"
	FILEINC scene3.091 "data/frames/scene3.091"
	FILEINC scene3.092 "data/frames/scene3.092"
	FILEINC scene3.093 "data/frames/scene3.093"
	FILEINC scene3.094 "data/frames/scene3.094"
	FILEINC scene3.095 "data/frames/scene3.095"
	FILEINC scene3.096 "data/frames/scene3.096"
	FILEINC scene3.097 "data/frames/scene3.097"
	FILEINC scene3.098 "data/frames/scene3.098"
	FILEINC scene3.099 "data/frames/scene3.099"
.ends

.section "scene3.100" superfree
	FILEINC scene3.100 "data/frames/scene3.100"
	FILEINC scene3.101 "data/frames/scene3.101"
	FILEINC scene3.102 "data/frames/scene3.102"
	FILEINC scene3.103 "data/frames/scene3.103"
	FILEINC scene3.104 "data/frames/scene3.104"
	FILEINC scene3.105 "data/frames/scene3.105"
	FILEINC scene3.106 "data/frames/scene3.106"
	FILEINC scene3.107 "data/frames/scene3.107"
	FILEINC scene3.108 "data/frames/scene3.108"
	FILEINC scene3.109 "data/frames/scene3.109"
.ends



