.section "scene16. lut" superfree
DemoScene16:
	.dw ((DemoScene16End-DemoScene16)/3)-2
	PTRLONG DemoScene16 scene16.000
	PTRLONG DemoScene16 scene16.001
	PTRLONG DemoScene16 scene16.002
	PTRLONG DemoScene16 scene16.003
	PTRLONG DemoScene16 scene16.004
	PTRLONG DemoScene16 scene16.005
	PTRLONG DemoScene16 scene16.006
	PTRLONG DemoScene16 scene16.007
	PTRLONG DemoScene16 scene16.008
	PTRLONG DemoScene16 scene16.009
	PTRLONG DemoScene16 scene16.010
	PTRLONG DemoScene16 scene16.011
	PTRLONG DemoScene16 scene16.012
	PTRLONG DemoScene16 scene16.013
	PTRLONG DemoScene16 scene16.014
	PTRLONG DemoScene16 scene16.015
	PTRLONG DemoScene16 scene16.016
	PTRLONG DemoScene16 scene16.017
	PTRLONG DemoScene16 scene16.018
	PTRLONG DemoScene16 scene16.019
	PTRLONG DemoScene16 scene16.020
	PTRLONG DemoScene16 scene16.021
	PTRLONG DemoScene16 scene16.022
	PTRLONG DemoScene16 scene16.023
	PTRLONG DemoScene16 scene16.024
	PTRLONG DemoScene16 scene16.025
	PTRLONG DemoScene16 scene16.026
	PTRLONG DemoScene16 scene16.027
	PTRLONG DemoScene16 scene16.028
	PTRLONG DemoScene16 scene16.029
	PTRLONG DemoScene16 scene16.030
	PTRLONG DemoScene16 scene16.031
	PTRLONG DemoScene16 scene16.032
	PTRLONG DemoScene16 scene16.033
	PTRLONG DemoScene16 scene16.034
	PTRLONG DemoScene16 scene16.035
	PTRLONG DemoScene16 scene16.036
	PTRLONG DemoScene16 scene16.037
	PTRLONG DemoScene16 scene16.038
	PTRLONG DemoScene16 scene16.039
	PTRLONG DemoScene16 scene16.040
	PTRLONG DemoScene16 scene16.041
	PTRLONG DemoScene16 scene16.042
	PTRLONG DemoScene16 scene16.043
	PTRLONG DemoScene16 scene16.044
	PTRLONG DemoScene16 scene16.045
	PTRLONG DemoScene16 scene16.046
	PTRLONG DemoScene16 scene16.047
	PTRLONG DemoScene16 scene16.048
	PTRLONG DemoScene16 scene16.049
	PTRLONG DemoScene16 scene16.050
	PTRLONG DemoScene16 scene16.051
	PTRLONG DemoScene16 scene16.052
	PTRLONG DemoScene16 scene16.053
	PTRLONG DemoScene16 scene16.054
	PTRLONG DemoScene16 scene16.055
	PTRLONG DemoScene16 scene16.056
	PTRLONG DemoScene16 scene16.057
	PTRLONG DemoScene16 scene16.058
	PTRLONG DemoScene16 scene16.059
	PTRLONG DemoScene16 scene16.060
	PTRLONG DemoScene16 scene16.061
	PTRLONG DemoScene16 scene16.062
	PTRLONG DemoScene16 scene16.063
	PTRLONG DemoScene16 scene16.064
	PTRLONG DemoScene16 scene16.065
	PTRLONG DemoScene16 scene16.066
	PTRLONG DemoScene16 scene16.067
	PTRLONG DemoScene16 scene16.068
	PTRLONG DemoScene16 scene16.069
	PTRLONG DemoScene16 scene16.070
	PTRLONG DemoScene16 scene16.071
	PTRLONG DemoScene16 scene16.072
	PTRLONG DemoScene16 scene16.073
	PTRLONG DemoScene16 scene16.074
	PTRLONG DemoScene16 scene16.075
	PTRLONG DemoScene16 scene16.076
	PTRLONG DemoScene16 scene16.077
	PTRLONG DemoScene16 scene16.078
	PTRLONG DemoScene16 scene16.079
	PTRLONG DemoScene16 scene16.080
	PTRLONG DemoScene16 scene16.081
	PTRLONG DemoScene16 scene16.082
	PTRLONG DemoScene16 scene16.083
	PTRLONG DemoScene16 scene16.084
	PTRLONG DemoScene16 scene16.085
	PTRLONG DemoScene16 scene16.086
	PTRLONG DemoScene16 scene16.087
	PTRLONG DemoScene16 scene16.088
	PTRLONG DemoScene16 scene16.089
	PTRLONG DemoScene16 scene16.090
	PTRLONG DemoScene16 scene16.091
	PTRLONG DemoScene16 scene16.092
	PTRLONG DemoScene16 scene16.093
	PTRLONG DemoScene16 scene16.094
	PTRLONG DemoScene16 scene16.095
	PTRLONG DemoScene16 scene16.096
	PTRLONG DemoScene16 scene16.097
	PTRLONG DemoScene16 scene16.098
	PTRLONG DemoScene16 scene16.099
	PTRLONG DemoScene16 scene16.100
	PTRLONG DemoScene16 scene16.101
	PTRLONG DemoScene16 scene16.102
	PTRLONG DemoScene16 scene16.103
	PTRLONG DemoScene16 scene16.104
	PTRLONG DemoScene16 scene16.105
	PTRLONG DemoScene16 scene16.106
	PTRLONG DemoScene16 scene16.107
	PTRLONG DemoScene16 scene16.108
	PTRLONG DemoScene16 scene16.109
	PTRLONG DemoScene16 scene16.110
	PTRLONG DemoScene16 scene16.111
	PTRLONG DemoScene16 scene16.112
	PTRLONG DemoScene16 scene16.113
	PTRLONG DemoScene16 scene16.114
	PTRLONG DemoScene16 scene16.115
	PTRLONG DemoScene16 scene16.116
	PTRLONG DemoScene16 scene16.117
	PTRLONG DemoScene16 scene16.118
	PTRLONG DemoScene16 scene16.119
	PTRLONG DemoScene16 scene16.120
	PTRLONG DemoScene16 scene16.121
	PTRLONG DemoScene16 scene16.122
	PTRLONG DemoScene16 scene16.123
	PTRLONG DemoScene16 scene16.124
	PTRLONG DemoScene16 scene16.125
	PTRLONG DemoScene16 scene16.126
	PTRLONG DemoScene16 scene16.127
	PTRLONG DemoScene16 scene16.128
	PTRLONG DemoScene16 scene16.129
	PTRLONG DemoScene16 scene16.130
	PTRLONG DemoScene16 scene16.131
	PTRLONG DemoScene16 scene16.132
	PTRLONG DemoScene16 scene16.133
	PTRLONG DemoScene16 scene16.134
	PTRLONG DemoScene16 scene16.135
	PTRLONG DemoScene16 scene16.136
	PTRLONG DemoScene16 scene16.137
	PTRLONG DemoScene16 scene16.138
	PTRLONG DemoScene16 scene16.139
	PTRLONG DemoScene16 scene16.140
	PTRLONG DemoScene16 scene16.141
	PTRLONG DemoScene16 scene16.142
	PTRLONG DemoScene16 scene16.143
	PTRLONG DemoScene16 scene16.144
	PTRLONG DemoScene16 scene16.145
	PTRLONG DemoScene16 scene16.146
	PTRLONG DemoScene16 scene16.147
	PTRLONG DemoScene16 scene16.148
	PTRLONG DemoScene16 scene16.149

DemoScene16End:

.ends

.section "scene16.000" superfree
	FILEINC scene16.000 "data/frames/scene16.000"
	FILEINC scene16.001 "data/frames/scene16.001"
	FILEINC scene16.002 "data/frames/scene16.002"
	FILEINC scene16.003 "data/frames/scene16.003"
	FILEINC scene16.004 "data/frames/scene16.004"
	FILEINC scene16.005 "data/frames/scene16.005"
	FILEINC scene16.006 "data/frames/scene16.006"
	FILEINC scene16.007 "data/frames/scene16.007"
	FILEINC scene16.008 "data/frames/scene16.008"
	FILEINC scene16.009 "data/frames/scene16.009"
.ends

.section "scene16.010" superfree
	FILEINC scene16.010 "data/frames/scene16.010"
	FILEINC scene16.011 "data/frames/scene16.011"
	FILEINC scene16.012 "data/frames/scene16.012"
	FILEINC scene16.013 "data/frames/scene16.013"
	FILEINC scene16.014 "data/frames/scene16.014"
	FILEINC scene16.015 "data/frames/scene16.015"
	FILEINC scene16.016 "data/frames/scene16.016"
	FILEINC scene16.017 "data/frames/scene16.017"
	FILEINC scene16.018 "data/frames/scene16.018"
	FILEINC scene16.019 "data/frames/scene16.019"
.ends

.section "scene16.020" superfree
	FILEINC scene16.020 "data/frames/scene16.020"
	FILEINC scene16.021 "data/frames/scene16.021"
	FILEINC scene16.022 "data/frames/scene16.022"
	FILEINC scene16.023 "data/frames/scene16.023"
	FILEINC scene16.024 "data/frames/scene16.024"
	FILEINC scene16.025 "data/frames/scene16.025"
	FILEINC scene16.026 "data/frames/scene16.026"
	FILEINC scene16.027 "data/frames/scene16.027"
	FILEINC scene16.028 "data/frames/scene16.028"
	FILEINC scene16.029 "data/frames/scene16.029"
.ends


.section "scene16.030" superfree
	FILEINC scene16.030 "data/frames/scene16.030"
	FILEINC scene16.031 "data/frames/scene16.031"
	FILEINC scene16.032 "data/frames/scene16.032"
	FILEINC scene16.033 "data/frames/scene16.033"
	FILEINC scene16.034 "data/frames/scene16.034"
	FILEINC scene16.035 "data/frames/scene16.035"
	FILEINC scene16.036 "data/frames/scene16.036"
	FILEINC scene16.037 "data/frames/scene16.037"
	FILEINC scene16.038 "data/frames/scene16.038"
	FILEINC scene16.039 "data/frames/scene16.039"
.ends


.section "scene16.040" superfree
	FILEINC scene16.040 "data/frames/scene16.040"
	FILEINC scene16.041 "data/frames/scene16.041"
	FILEINC scene16.042 "data/frames/scene16.042"
	FILEINC scene16.043 "data/frames/scene16.043"
	FILEINC scene16.044 "data/frames/scene16.044"
	FILEINC scene16.045 "data/frames/scene16.045"
	FILEINC scene16.046 "data/frames/scene16.046"
	FILEINC scene16.047 "data/frames/scene16.047"
	FILEINC scene16.048 "data/frames/scene16.048"
	FILEINC scene16.049 "data/frames/scene16.049"
.ends


.section "scene16.050" superfree
	FILEINC scene16.050 "data/frames/scene16.050"
	FILEINC scene16.051 "data/frames/scene16.051"
	FILEINC scene16.052 "data/frames/scene16.052"
	FILEINC scene16.053 "data/frames/scene16.053"
	FILEINC scene16.054 "data/frames/scene16.054"
	FILEINC scene16.055 "data/frames/scene16.055"
	FILEINC scene16.056 "data/frames/scene16.056"
	FILEINC scene16.057 "data/frames/scene16.057"
	FILEINC scene16.058 "data/frames/scene16.058"
	FILEINC scene16.059 "data/frames/scene16.059"
.ends


.section "scene16.060" superfree
	FILEINC scene16.060 "data/frames/scene16.060"
	FILEINC scene16.061 "data/frames/scene16.061"
	FILEINC scene16.062 "data/frames/scene16.062"
	FILEINC scene16.063 "data/frames/scene16.063"
	FILEINC scene16.064 "data/frames/scene16.064"
	FILEINC scene16.065 "data/frames/scene16.065"
	FILEINC scene16.066 "data/frames/scene16.066"
	FILEINC scene16.067 "data/frames/scene16.067"
	FILEINC scene16.068 "data/frames/scene16.068"
	FILEINC scene16.069 "data/frames/scene16.069"
.ends


.section "scene16.070" superfree
	FILEINC scene16.070 "data/frames/scene16.070"
	FILEINC scene16.071 "data/frames/scene16.071"
	FILEINC scene16.072 "data/frames/scene16.072"
	FILEINC scene16.073 "data/frames/scene16.073"
	FILEINC scene16.074 "data/frames/scene16.074"
	FILEINC scene16.075 "data/frames/scene16.075"
	FILEINC scene16.076 "data/frames/scene16.076"
	FILEINC scene16.077 "data/frames/scene16.077"
	FILEINC scene16.078 "data/frames/scene16.078"
	FILEINC scene16.079 "data/frames/scene16.079"
.ends


.section "scene16.080" superfree
	FILEINC scene16.080 "data/frames/scene16.080"
	FILEINC scene16.081 "data/frames/scene16.081"
	FILEINC scene16.082 "data/frames/scene16.082"
	FILEINC scene16.083 "data/frames/scene16.083"
	FILEINC scene16.084 "data/frames/scene16.084"
	FILEINC scene16.085 "data/frames/scene16.085"
	FILEINC scene16.086 "data/frames/scene16.086"
	FILEINC scene16.087 "data/frames/scene16.087"
	FILEINC scene16.088 "data/frames/scene16.088"
	FILEINC scene16.089 "data/frames/scene16.089"
.ends


.section "scene16.090" superfree
	FILEINC scene16.090 "data/frames/scene16.090"
	FILEINC scene16.091 "data/frames/scene16.091"
	FILEINC scene16.092 "data/frames/scene16.092"
	FILEINC scene16.093 "data/frames/scene16.093"
	FILEINC scene16.094 "data/frames/scene16.094"
	FILEINC scene16.095 "data/frames/scene16.095"
	FILEINC scene16.096 "data/frames/scene16.096"
	FILEINC scene16.097 "data/frames/scene16.097"
	FILEINC scene16.098 "data/frames/scene16.098"
	FILEINC scene16.099 "data/frames/scene16.099"
.ends

.section "scene16.100" superfree
	FILEINC scene16.100 "data/frames/scene16.100"
	FILEINC scene16.101 "data/frames/scene16.101"
	FILEINC scene16.102 "data/frames/scene16.102"
	FILEINC scene16.103 "data/frames/scene16.103"
	FILEINC scene16.104 "data/frames/scene16.104"
	FILEINC scene16.105 "data/frames/scene16.105"
	FILEINC scene16.106 "data/frames/scene16.106"
	FILEINC scene16.107 "data/frames/scene16.107"
	FILEINC scene16.108 "data/frames/scene16.108"
	FILEINC scene16.109 "data/frames/scene16.109"
.ends

.section "scene16.110" superfree
	FILEINC scene16.110 "data/frames/scene16.110"
	FILEINC scene16.111 "data/frames/scene16.111"
	FILEINC scene16.112 "data/frames/scene16.112"
	FILEINC scene16.113 "data/frames/scene16.113"
	FILEINC scene16.114 "data/frames/scene16.114"
	FILEINC scene16.115 "data/frames/scene16.115"
	FILEINC scene16.116 "data/frames/scene16.116"
	FILEINC scene16.117 "data/frames/scene16.117"
	FILEINC scene16.118 "data/frames/scene16.118"
	FILEINC scene16.119 "data/frames/scene16.119"
.ends

.section "scene16.120" superfree
	FILEINC scene16.120 "data/frames/scene16.120"
	FILEINC scene16.121 "data/frames/scene16.121"
	FILEINC scene16.122 "data/frames/scene16.122"
	FILEINC scene16.123 "data/frames/scene16.123"
	FILEINC scene16.124 "data/frames/scene16.124"
	FILEINC scene16.125 "data/frames/scene16.125"
	FILEINC scene16.126 "data/frames/scene16.126"
	FILEINC scene16.127 "data/frames/scene16.127"
	FILEINC scene16.128 "data/frames/scene16.128"
	FILEINC scene16.129 "data/frames/scene16.129"
.ends


.section "scene16.130" superfree
	FILEINC scene16.130 "data/frames/scene16.130"
	FILEINC scene16.131 "data/frames/scene16.131"
	FILEINC scene16.132 "data/frames/scene16.132"
	FILEINC scene16.133 "data/frames/scene16.133"
	FILEINC scene16.134 "data/frames/scene16.134"
	FILEINC scene16.135 "data/frames/scene16.135"
	FILEINC scene16.136 "data/frames/scene16.136"
	FILEINC scene16.137 "data/frames/scene16.137"
	FILEINC scene16.138 "data/frames/scene16.138"
	FILEINC scene16.139 "data/frames/scene16.139"
.ends


.section "scene16.140" superfree
	FILEINC scene16.140 "data/frames/scene16.140"
	FILEINC scene16.141 "data/frames/scene16.141"
	FILEINC scene16.142 "data/frames/scene16.142"
	FILEINC scene16.143 "data/frames/scene16.143"
	FILEINC scene16.144 "data/frames/scene16.144"
	FILEINC scene16.145 "data/frames/scene16.145"
	FILEINC scene16.146 "data/frames/scene16.146"
	FILEINC scene16.147 "data/frames/scene16.147"
	FILEINC scene16.148 "data/frames/scene16.148"
	FILEINC scene16.149 "data/frames/scene16.149"
.ends
