.section "scene13. lut" superfree
DemoScene13:
	.dw ((DemoScene13End-DemoScene13)/3)-2
	PTRLONG DemoScene13 scene11.000
	PTRLONG DemoScene13 scene11.001
	PTRLONG DemoScene13 scene11.002
	PTRLONG DemoScene13 scene11.003
	PTRLONG DemoScene13 scene11.004
	PTRLONG DemoScene13 scene11.005
	PTRLONG DemoScene13 scene11.006
	PTRLONG DemoScene13 scene11.007
	PTRLONG DemoScene13 scene11.008
	PTRLONG DemoScene13 scene11.009
	PTRLONG DemoScene13 scene11.010

DemoScene13End:

.ends
