.section "scene7. lut" superfree
DemoScene7:
	.dw ((DemoScene7End-DemoScene7)/3)-2
	PTRLONG DemoScene7 scene7.000
	PTRLONG DemoScene7 scene7.001
	PTRLONG DemoScene7 scene7.002
	PTRLONG DemoScene7 scene7.003
	PTRLONG DemoScene7 scene7.004
	PTRLONG DemoScene7 scene7.005
	PTRLONG DemoScene7 scene7.006
	PTRLONG DemoScene7 scene7.007
	PTRLONG DemoScene7 scene7.008
	PTRLONG DemoScene7 scene7.009
	PTRLONG DemoScene7 scene7.010
	PTRLONG DemoScene7 scene7.011
	PTRLONG DemoScene7 scene7.012
	PTRLONG DemoScene7 scene7.013
	PTRLONG DemoScene7 scene7.014
	PTRLONG DemoScene7 scene7.015
	PTRLONG DemoScene7 scene7.016
	PTRLONG DemoScene7 scene7.017
	PTRLONG DemoScene7 scene7.018
	PTRLONG DemoScene7 scene7.019
	PTRLONG DemoScene7 scene7.020
	PTRLONG DemoScene7 scene7.021
	PTRLONG DemoScene7 scene7.022
	PTRLONG DemoScene7 scene7.023
	PTRLONG DemoScene7 scene7.024
	PTRLONG DemoScene7 scene7.025
	PTRLONG DemoScene7 scene7.026
	PTRLONG DemoScene7 scene7.027
	PTRLONG DemoScene7 scene7.028
	PTRLONG DemoScene7 scene7.029

DemoScene7End:

.ends

.section "scene7.000" superfree
	FILEINC scene7.000 "data/frames/scene7.000"
	FILEINC scene7.001 "data/frames/scene7.001"
	FILEINC scene7.002 "data/frames/scene7.002"
	FILEINC scene7.003 "data/frames/scene7.003"
	FILEINC scene7.004 "data/frames/scene7.004"
	FILEINC scene7.005 "data/frames/scene7.005"
	FILEINC scene7.006 "data/frames/scene7.006"
	FILEINC scene7.007 "data/frames/scene7.007"
	FILEINC scene7.008 "data/frames/scene7.008"
	FILEINC scene7.009 "data/frames/scene7.009"
.ends

.section "scene7.010" superfree
	FILEINC scene7.010 "data/frames/scene7.010"
	FILEINC scene7.011 "data/frames/scene7.011"
	FILEINC scene7.012 "data/frames/scene7.012"
	FILEINC scene7.013 "data/frames/scene7.013"
	FILEINC scene7.014 "data/frames/scene7.014"
	FILEINC scene7.015 "data/frames/scene7.015"
	FILEINC scene7.016 "data/frames/scene7.016"
	FILEINC scene7.017 "data/frames/scene7.017"
	FILEINC scene7.018 "data/frames/scene7.018"
	FILEINC scene7.019 "data/frames/scene7.019"
.ends

.section "scene7.020" superfree
	FILEINC scene7.020 "data/frames/scene7.020"
	FILEINC scene7.021 "data/frames/scene7.021"
	FILEINC scene7.022 "data/frames/scene7.022"
	FILEINC scene7.023 "data/frames/scene7.023"
	FILEINC scene7.024 "data/frames/scene7.024"
	FILEINC scene7.025 "data/frames/scene7.025"
	FILEINC scene7.026 "data/frames/scene7.026"
	FILEINC scene7.027 "data/frames/scene7.027"
	FILEINC scene7.028 "data/frames/scene7.028"
	FILEINC scene7.029 "data/frames/scene7.029"
.ends
