.section "scene12. lut" superfree
DemoScene12:
	.dw ((DemoScene12End-DemoScene12)/3)-2
	PTRLONG DemoScene12 scene10.000
	PTRLONG DemoScene12 scene10.001
	PTRLONG DemoScene12 scene10.002
	PTRLONG DemoScene12 scene10.003
	PTRLONG DemoScene12 scene10.004
	PTRLONG DemoScene12 scene10.005
	PTRLONG DemoScene12 scene10.006
	PTRLONG DemoScene12 scene10.007
	PTRLONG DemoScene12 scene10.008
	PTRLONG DemoScene12 scene10.009


DemoScene12End:

.ends


