.section "scene6. lut" superfree
DemoScene6:
	.dw ((DemoScene6End-DemoScene6)/3)-2
	PTRLONG DemoScene6 scene6.000
	PTRLONG DemoScene6 scene6.001
	PTRLONG DemoScene6 scene6.002
	PTRLONG DemoScene6 scene6.003
	PTRLONG DemoScene6 scene6.004
	PTRLONG DemoScene6 scene6.005
	PTRLONG DemoScene6 scene6.006
	PTRLONG DemoScene6 scene6.007
	PTRLONG DemoScene6 scene6.008
	PTRLONG DemoScene6 scene6.009
	PTRLONG DemoScene6 scene6.010
	PTRLONG DemoScene6 scene6.011
	PTRLONG DemoScene6 scene6.012
	PTRLONG DemoScene6 scene6.013
	PTRLONG DemoScene6 scene6.014
	PTRLONG DemoScene6 scene6.015
	PTRLONG DemoScene6 scene6.016
	PTRLONG DemoScene6 scene6.017
	PTRLONG DemoScene6 scene6.018
	PTRLONG DemoScene6 scene6.019
	PTRLONG DemoScene6 scene6.020
	PTRLONG DemoScene6 scene6.021
	PTRLONG DemoScene6 scene6.022
	PTRLONG DemoScene6 scene6.023
	PTRLONG DemoScene6 scene6.024
	PTRLONG DemoScene6 scene6.025
	PTRLONG DemoScene6 scene6.026
	PTRLONG DemoScene6 scene6.027
	PTRLONG DemoScene6 scene6.028
	PTRLONG DemoScene6 scene6.029
	PTRLONG DemoScene6 scene6.030
	PTRLONG DemoScene6 scene6.031
	PTRLONG DemoScene6 scene6.032
	PTRLONG DemoScene6 scene6.033
	PTRLONG DemoScene6 scene6.034
	PTRLONG DemoScene6 scene6.035
	PTRLONG DemoScene6 scene6.036
	PTRLONG DemoScene6 scene6.037
	PTRLONG DemoScene6 scene6.038
	PTRLONG DemoScene6 scene6.039
	PTRLONG DemoScene6 scene6.040
	PTRLONG DemoScene6 scene6.041
	PTRLONG DemoScene6 scene6.042
	PTRLONG DemoScene6 scene6.043
	PTRLONG DemoScene6 scene6.044
	PTRLONG DemoScene6 scene6.045
	PTRLONG DemoScene6 scene6.046
	PTRLONG DemoScene6 scene6.047
	PTRLONG DemoScene6 scene6.048
	PTRLONG DemoScene6 scene6.049
	PTRLONG DemoScene6 scene6.050
	PTRLONG DemoScene6 scene6.051
	PTRLONG DemoScene6 scene6.052
	PTRLONG DemoScene6 scene6.053
	PTRLONG DemoScene6 scene6.054
	PTRLONG DemoScene6 scene6.055
	PTRLONG DemoScene6 scene6.056
	PTRLONG DemoScene6 scene6.057
	PTRLONG DemoScene6 scene6.058
	PTRLONG DemoScene6 scene6.059
	PTRLONG DemoScene6 scene6.060
	PTRLONG DemoScene6 scene6.061
	PTRLONG DemoScene6 scene6.062
	PTRLONG DemoScene6 scene6.063
	PTRLONG DemoScene6 scene6.064
	PTRLONG DemoScene6 scene6.065
	PTRLONG DemoScene6 scene6.066
	PTRLONG DemoScene6 scene6.067
	PTRLONG DemoScene6 scene6.068
	PTRLONG DemoScene6 scene6.069
	PTRLONG DemoScene6 scene6.070
	PTRLONG DemoScene6 scene6.071
	PTRLONG DemoScene6 scene6.072
	PTRLONG DemoScene6 scene6.073
	PTRLONG DemoScene6 scene6.074
	PTRLONG DemoScene6 scene6.075
	PTRLONG DemoScene6 scene6.076
	PTRLONG DemoScene6 scene6.077
	PTRLONG DemoScene6 scene6.078
	PTRLONG DemoScene6 scene6.079
	PTRLONG DemoScene6 scene6.080
	PTRLONG DemoScene6 scene6.081
	PTRLONG DemoScene6 scene6.082
	PTRLONG DemoScene6 scene6.083
	PTRLONG DemoScene6 scene6.084
	PTRLONG DemoScene6 scene6.085
	PTRLONG DemoScene6 scene6.086
	PTRLONG DemoScene6 scene6.087
	PTRLONG DemoScene6 scene6.088
	PTRLONG DemoScene6 scene6.089
	PTRLONG DemoScene6 scene6.090
	PTRLONG DemoScene6 scene6.091
	PTRLONG DemoScene6 scene6.092
	PTRLONG DemoScene6 scene6.093
	PTRLONG DemoScene6 scene6.094
	PTRLONG DemoScene6 scene6.095
	PTRLONG DemoScene6 scene6.096
	PTRLONG DemoScene6 scene6.097
	PTRLONG DemoScene6 scene6.098
	PTRLONG DemoScene6 scene6.099
	PTRLONG DemoScene6 scene6.100
	PTRLONG DemoScene6 scene6.101
	PTRLONG DemoScene6 scene6.102
	PTRLONG DemoScene6 scene6.103
	PTRLONG DemoScene6 scene6.104
	PTRLONG DemoScene6 scene6.105
	PTRLONG DemoScene6 scene6.106
	PTRLONG DemoScene6 scene6.107
	PTRLONG DemoScene6 scene6.108
	PTRLONG DemoScene6 scene6.109
	PTRLONG DemoScene6 scene6.110
	PTRLONG DemoScene6 scene6.111
	PTRLONG DemoScene6 scene6.112
	PTRLONG DemoScene6 scene6.113
	PTRLONG DemoScene6 scene6.114
	PTRLONG DemoScene6 scene6.115
	PTRLONG DemoScene6 scene6.116
	PTRLONG DemoScene6 scene6.117
	PTRLONG DemoScene6 scene6.118
	PTRLONG DemoScene6 scene6.119
	PTRLONG DemoScene6 scene6.120
	PTRLONG DemoScene6 scene6.121
	PTRLONG DemoScene6 scene6.122
	PTRLONG DemoScene6 scene6.123
	PTRLONG DemoScene6 scene6.124
	PTRLONG DemoScene6 scene6.125
	PTRLONG DemoScene6 scene6.126
	PTRLONG DemoScene6 scene6.127
	PTRLONG DemoScene6 scene6.128
	PTRLONG DemoScene6 scene6.129

DemoScene6End:

.ends

.section "scene6.000" superfree
	FILEINC scene6.000 "data/frames/scene6.000"
	FILEINC scene6.001 "data/frames/scene6.001"
	FILEINC scene6.002 "data/frames/scene6.002"
	FILEINC scene6.003 "data/frames/scene6.003"
	FILEINC scene6.004 "data/frames/scene6.004"
	FILEINC scene6.005 "data/frames/scene6.005"
	FILEINC scene6.006 "data/frames/scene6.006"
	FILEINC scene6.007 "data/frames/scene6.007"
	FILEINC scene6.008 "data/frames/scene6.008"
	FILEINC scene6.009 "data/frames/scene6.009"
.ends

.section "scene6.010" superfree
	FILEINC scene6.010 "data/frames/scene6.010"
	FILEINC scene6.011 "data/frames/scene6.011"
	FILEINC scene6.012 "data/frames/scene6.012"
	FILEINC scene6.013 "data/frames/scene6.013"
	FILEINC scene6.014 "data/frames/scene6.014"
	FILEINC scene6.015 "data/frames/scene6.015"
	FILEINC scene6.016 "data/frames/scene6.016"
	FILEINC scene6.017 "data/frames/scene6.017"
	FILEINC scene6.018 "data/frames/scene6.018"
	FILEINC scene6.019 "data/frames/scene6.019"
.ends

.section "scene6.020" superfree
	FILEINC scene6.020 "data/frames/scene6.020"
	FILEINC scene6.021 "data/frames/scene6.021"
	FILEINC scene6.022 "data/frames/scene6.022"
	FILEINC scene6.023 "data/frames/scene6.023"
	FILEINC scene6.024 "data/frames/scene6.024"
	FILEINC scene6.025 "data/frames/scene6.025"
	FILEINC scene6.026 "data/frames/scene6.026"
	FILEINC scene6.027 "data/frames/scene6.027"
	FILEINC scene6.028 "data/frames/scene6.028"
	FILEINC scene6.029 "data/frames/scene6.029"
.ends


.section "scene6.030" superfree
	FILEINC scene6.030 "data/frames/scene6.030"
	FILEINC scene6.031 "data/frames/scene6.031"
	FILEINC scene6.032 "data/frames/scene6.032"
	FILEINC scene6.033 "data/frames/scene6.033"
	FILEINC scene6.034 "data/frames/scene6.034"
	FILEINC scene6.035 "data/frames/scene6.035"
	FILEINC scene6.036 "data/frames/scene6.036"
	FILEINC scene6.037 "data/frames/scene6.037"
	FILEINC scene6.038 "data/frames/scene6.038"
	FILEINC scene6.039 "data/frames/scene6.039"
.ends


.section "scene6.040" superfree
	FILEINC scene6.040 "data/frames/scene6.040"
	FILEINC scene6.041 "data/frames/scene6.041"
	FILEINC scene6.042 "data/frames/scene6.042"
	FILEINC scene6.043 "data/frames/scene6.043"
	FILEINC scene6.044 "data/frames/scene6.044"
	FILEINC scene6.045 "data/frames/scene6.045"
	FILEINC scene6.046 "data/frames/scene6.046"
	FILEINC scene6.047 "data/frames/scene6.047"
	FILEINC scene6.048 "data/frames/scene6.048"
	FILEINC scene6.049 "data/frames/scene6.049"
.ends


.section "scene6.050" superfree
	FILEINC scene6.050 "data/frames/scene6.050"
	FILEINC scene6.051 "data/frames/scene6.051"
	FILEINC scene6.052 "data/frames/scene6.052"
	FILEINC scene6.053 "data/frames/scene6.053"
	FILEINC scene6.054 "data/frames/scene6.054"
	FILEINC scene6.055 "data/frames/scene6.055"
	FILEINC scene6.056 "data/frames/scene6.056"
	FILEINC scene6.057 "data/frames/scene6.057"
	FILEINC scene6.058 "data/frames/scene6.058"
	FILEINC scene6.059 "data/frames/scene6.059"
.ends


.section "scene6.060" superfree
	FILEINC scene6.060 "data/frames/scene6.060"
	FILEINC scene6.061 "data/frames/scene6.061"
	FILEINC scene6.062 "data/frames/scene6.062"
	FILEINC scene6.063 "data/frames/scene6.063"
	FILEINC scene6.064 "data/frames/scene6.064"
	FILEINC scene6.065 "data/frames/scene6.065"
	FILEINC scene6.066 "data/frames/scene6.066"
	FILEINC scene6.067 "data/frames/scene6.067"
	FILEINC scene6.068 "data/frames/scene6.068"
	FILEINC scene6.069 "data/frames/scene6.069"
.ends


.section "scene6.070" superfree
	FILEINC scene6.070 "data/frames/scene6.070"
	FILEINC scene6.071 "data/frames/scene6.071"
	FILEINC scene6.072 "data/frames/scene6.072"
	FILEINC scene6.073 "data/frames/scene6.073"
	FILEINC scene6.074 "data/frames/scene6.074"
	FILEINC scene6.075 "data/frames/scene6.075"
	FILEINC scene6.076 "data/frames/scene6.076"
	FILEINC scene6.077 "data/frames/scene6.077"
	FILEINC scene6.078 "data/frames/scene6.078"
	FILEINC scene6.079 "data/frames/scene6.079"
.ends


.section "scene6.080" superfree
	FILEINC scene6.080 "data/frames/scene6.080"
	FILEINC scene6.081 "data/frames/scene6.081"
	FILEINC scene6.082 "data/frames/scene6.082"
	FILEINC scene6.083 "data/frames/scene6.083"
	FILEINC scene6.084 "data/frames/scene6.084"
	FILEINC scene6.085 "data/frames/scene6.085"
	FILEINC scene6.086 "data/frames/scene6.086"
	FILEINC scene6.087 "data/frames/scene6.087"
	FILEINC scene6.088 "data/frames/scene6.088"
	FILEINC scene6.089 "data/frames/scene6.089"
.ends


.section "scene6.090" superfree
	FILEINC scene6.090 "data/frames/scene6.090"
	FILEINC scene6.091 "data/frames/scene6.091"
	FILEINC scene6.092 "data/frames/scene6.092"
	FILEINC scene6.093 "data/frames/scene6.093"
	FILEINC scene6.094 "data/frames/scene6.094"
	FILEINC scene6.095 "data/frames/scene6.095"
	FILEINC scene6.096 "data/frames/scene6.096"
	FILEINC scene6.097 "data/frames/scene6.097"
	FILEINC scene6.098 "data/frames/scene6.098"
	FILEINC scene6.099 "data/frames/scene6.099"
.ends

.section "scene6.100" superfree
	FILEINC scene6.100 "data/frames/scene6.100"
	FILEINC scene6.101 "data/frames/scene6.101"
	FILEINC scene6.102 "data/frames/scene6.102"
	FILEINC scene6.103 "data/frames/scene6.103"
	FILEINC scene6.104 "data/frames/scene6.104"
	FILEINC scene6.105 "data/frames/scene6.105"
	FILEINC scene6.106 "data/frames/scene6.106"
	FILEINC scene6.107 "data/frames/scene6.107"
	FILEINC scene6.108 "data/frames/scene6.108"
	FILEINC scene6.109 "data/frames/scene6.109"
.ends

.section "scene6.110" superfree
	FILEINC scene6.110 "data/frames/scene6.110"
	FILEINC scene6.111 "data/frames/scene6.111"
	FILEINC scene6.112 "data/frames/scene6.112"
	FILEINC scene6.113 "data/frames/scene6.113"
	FILEINC scene6.114 "data/frames/scene6.114"
	FILEINC scene6.115 "data/frames/scene6.115"
	FILEINC scene6.116 "data/frames/scene6.116"
	FILEINC scene6.117 "data/frames/scene6.117"
	FILEINC scene6.118 "data/frames/scene6.118"
	FILEINC scene6.119 "data/frames/scene6.119"
.ends

.section "scene6.120" superfree
	FILEINC scene6.120 "data/frames/scene6.120"
	FILEINC scene6.121 "data/frames/scene6.121"
	FILEINC scene6.122 "data/frames/scene6.122"
	FILEINC scene6.123 "data/frames/scene6.123"
	FILEINC scene6.124 "data/frames/scene6.124"
	FILEINC scene6.125 "data/frames/scene6.125"
	FILEINC scene6.126 "data/frames/scene6.126"
	FILEINC scene6.127 "data/frames/scene6.127"
	FILEINC scene6.128 "data/frames/scene6.128"
	FILEINC scene6.129 "data/frames/scene6.129"
.ends

