.section "scene17. lut" superfree
DemoScene17:
	.dw ((DemoScene17End-DemoScene17)/3)-2
	PTRLONG DemoScene17 scene17.000
	PTRLONG DemoScene17 scene17.001
	PTRLONG DemoScene17 scene17.002
	PTRLONG DemoScene17 scene17.003
	PTRLONG DemoScene17 scene17.004
	PTRLONG DemoScene17 scene17.005
	PTRLONG DemoScene17 scene17.006
	PTRLONG DemoScene17 scene17.007
	PTRLONG DemoScene17 scene17.008
	PTRLONG DemoScene17 scene17.009
	PTRLONG DemoScene17 scene17.010
	PTRLONG DemoScene17 scene17.011
	PTRLONG DemoScene17 scene17.012
	PTRLONG DemoScene17 scene17.013
	PTRLONG DemoScene17 scene17.014
	PTRLONG DemoScene17 scene17.015
	PTRLONG DemoScene17 scene17.016
	PTRLONG DemoScene17 scene17.017
	PTRLONG DemoScene17 scene17.018
	PTRLONG DemoScene17 scene17.019
	PTRLONG DemoScene17 scene17.020
	PTRLONG DemoScene17 scene17.021
	PTRLONG DemoScene17 scene17.022
	PTRLONG DemoScene17 scene17.023
	PTRLONG DemoScene17 scene17.024
	PTRLONG DemoScene17 scene17.025
	PTRLONG DemoScene17 scene17.026
	PTRLONG DemoScene17 scene17.027
	PTRLONG DemoScene17 scene17.028
	PTRLONG DemoScene17 scene17.029
	PTRLONG DemoScene17 scene17.030
	PTRLONG DemoScene17 scene17.031
	PTRLONG DemoScene17 scene17.032
	PTRLONG DemoScene17 scene17.033
	PTRLONG DemoScene17 scene17.034
	PTRLONG DemoScene17 scene17.035
	PTRLONG DemoScene17 scene17.036
	PTRLONG DemoScene17 scene17.037
	PTRLONG DemoScene17 scene17.038
	PTRLONG DemoScene17 scene17.039
	PTRLONG DemoScene17 scene17.040
	PTRLONG DemoScene17 scene17.041
	PTRLONG DemoScene17 scene17.042
	PTRLONG DemoScene17 scene17.043
	PTRLONG DemoScene17 scene17.044
	PTRLONG DemoScene17 scene17.045
	PTRLONG DemoScene17 scene17.046
	PTRLONG DemoScene17 scene17.047
	PTRLONG DemoScene17 scene17.048
	PTRLONG DemoScene17 scene17.049
	PTRLONG DemoScene17 scene17.050
	PTRLONG DemoScene17 scene17.051
	PTRLONG DemoScene17 scene17.052
	PTRLONG DemoScene17 scene17.053
	PTRLONG DemoScene17 scene17.054
	PTRLONG DemoScene17 scene17.055
	PTRLONG DemoScene17 scene17.056
	PTRLONG DemoScene17 scene17.057
	PTRLONG DemoScene17 scene17.058
	PTRLONG DemoScene17 scene17.059
	PTRLONG DemoScene17 scene17.060
	PTRLONG DemoScene17 scene17.061
	PTRLONG DemoScene17 scene17.062
	PTRLONG DemoScene17 scene17.063
	PTRLONG DemoScene17 scene17.064
	PTRLONG DemoScene17 scene17.065
	PTRLONG DemoScene17 scene17.066
	PTRLONG DemoScene17 scene17.067
	PTRLONG DemoScene17 scene17.068
	PTRLONG DemoScene17 scene17.069
	PTRLONG DemoScene17 scene17.070
	PTRLONG DemoScene17 scene17.071
	PTRLONG DemoScene17 scene17.072
	PTRLONG DemoScene17 scene17.073
	PTRLONG DemoScene17 scene17.074
	PTRLONG DemoScene17 scene17.075
	PTRLONG DemoScene17 scene17.076
	PTRLONG DemoScene17 scene17.077
	PTRLONG DemoScene17 scene17.078
	PTRLONG DemoScene17 scene17.079

DemoScene17End:

.ends

.section "scene17.000" superfree
	FILEINC scene17.000 "data/frames/scene17.000"
	FILEINC scene17.001 "data/frames/scene17.001"
	FILEINC scene17.002 "data/frames/scene17.002"
	FILEINC scene17.003 "data/frames/scene17.003"
	FILEINC scene17.004 "data/frames/scene17.004"
	FILEINC scene17.005 "data/frames/scene17.005"
	FILEINC scene17.006 "data/frames/scene17.006"
	FILEINC scene17.007 "data/frames/scene17.007"
	FILEINC scene17.008 "data/frames/scene17.008"
	FILEINC scene17.009 "data/frames/scene17.009"
.ends

.section "scene17.010" superfree
	FILEINC scene17.010 "data/frames/scene17.010"
	FILEINC scene17.011 "data/frames/scene17.011"
	FILEINC scene17.012 "data/frames/scene17.012"
	FILEINC scene17.013 "data/frames/scene17.013"
	FILEINC scene17.014 "data/frames/scene17.014"
	FILEINC scene17.015 "data/frames/scene17.015"
	FILEINC scene17.016 "data/frames/scene17.016"
	FILEINC scene17.017 "data/frames/scene17.017"
	FILEINC scene17.018 "data/frames/scene17.018"
	FILEINC scene17.019 "data/frames/scene17.019"
.ends

.section "scene17.020" superfree
	FILEINC scene17.020 "data/frames/scene17.020"
	FILEINC scene17.021 "data/frames/scene17.021"
	FILEINC scene17.022 "data/frames/scene17.022"
	FILEINC scene17.023 "data/frames/scene17.023"
	FILEINC scene17.024 "data/frames/scene17.024"
	FILEINC scene17.025 "data/frames/scene17.025"
	FILEINC scene17.026 "data/frames/scene17.026"
	FILEINC scene17.027 "data/frames/scene17.027"
	FILEINC scene17.028 "data/frames/scene17.028"
	FILEINC scene17.029 "data/frames/scene17.029"
.ends


.section "scene17.030" superfree
	FILEINC scene17.030 "data/frames/scene17.030"
	FILEINC scene17.031 "data/frames/scene17.031"
	FILEINC scene17.032 "data/frames/scene17.032"
	FILEINC scene17.033 "data/frames/scene17.033"
	FILEINC scene17.034 "data/frames/scene17.034"
	FILEINC scene17.035 "data/frames/scene17.035"
	FILEINC scene17.036 "data/frames/scene17.036"
	FILEINC scene17.037 "data/frames/scene17.037"
	FILEINC scene17.038 "data/frames/scene17.038"
	FILEINC scene17.039 "data/frames/scene17.039"
.ends


.section "scene17.040" superfree
	FILEINC scene17.040 "data/frames/scene17.040"
	FILEINC scene17.041 "data/frames/scene17.041"
	FILEINC scene17.042 "data/frames/scene17.042"
	FILEINC scene17.043 "data/frames/scene17.043"
	FILEINC scene17.044 "data/frames/scene17.044"
	FILEINC scene17.045 "data/frames/scene17.045"
	FILEINC scene17.046 "data/frames/scene17.046"
	FILEINC scene17.047 "data/frames/scene17.047"
	FILEINC scene17.048 "data/frames/scene17.048"
	FILEINC scene17.049 "data/frames/scene17.049"
.ends


.section "scene17.050" superfree
	FILEINC scene17.050 "data/frames/scene17.050"
	FILEINC scene17.051 "data/frames/scene17.051"
	FILEINC scene17.052 "data/frames/scene17.052"
	FILEINC scene17.053 "data/frames/scene17.053"
	FILEINC scene17.054 "data/frames/scene17.054"
	FILEINC scene17.055 "data/frames/scene17.055"
	FILEINC scene17.056 "data/frames/scene17.056"
	FILEINC scene17.057 "data/frames/scene17.057"
	FILEINC scene17.058 "data/frames/scene17.058"
	FILEINC scene17.059 "data/frames/scene17.059"
.ends


.section "scene17.060" superfree
	FILEINC scene17.060 "data/frames/scene17.060"
	FILEINC scene17.061 "data/frames/scene17.061"
	FILEINC scene17.062 "data/frames/scene17.062"
	FILEINC scene17.063 "data/frames/scene17.063"
	FILEINC scene17.064 "data/frames/scene17.064"
	FILEINC scene17.065 "data/frames/scene17.065"
	FILEINC scene17.066 "data/frames/scene17.066"
	FILEINC scene17.067 "data/frames/scene17.067"
	FILEINC scene17.068 "data/frames/scene17.068"
	FILEINC scene17.069 "data/frames/scene17.069"
.ends


.section "scene17.070" superfree
	FILEINC scene17.070 "data/frames/scene17.070"
	FILEINC scene17.071 "data/frames/scene17.071"
	FILEINC scene17.072 "data/frames/scene17.072"
	FILEINC scene17.073 "data/frames/scene17.073"
	FILEINC scene17.074 "data/frames/scene17.074"
	FILEINC scene17.075 "data/frames/scene17.075"
	FILEINC scene17.076 "data/frames/scene17.076"
	FILEINC scene17.077 "data/frames/scene17.077"
	FILEINC scene17.078 "data/frames/scene17.078"
	FILEINC scene17.079 "data/frames/scene17.079"
.ends
